/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TaiKhoanController;
import Model.TaiKhoan;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DHC
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formDK = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        disable = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        show = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblMaNV = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formDK.setBackground(new java.awt.Color(25, 118, 211));
        formDK.setForeground(new java.awt.Color(255, 255, 255));
        formDK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Register");
        formDK.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 384, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username");
        formDK.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 94, 286, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã Nhân Viên");
        formDK.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        lblUsername.setForeground(new java.awt.Color(255, 255, 255));
        lblUsername.setText("_________________________________");
        formDK.add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 280, -1));

        disable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_invisible_32px.png"))); // NOI18N
        disable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disableMouseClicked(evt);
            }
        });
        formDK.add(disable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 27));

        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("_________________________________");
        formDK.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 196, 290, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_contacts_32px_3.png"))); // NOI18N
        formDK.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 27));

        btnRegister.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(0, 102, 255));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        formDK.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 320, -1));

        txtusername.setBackground(new java.awt.Color(25, 118, 211));
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setBorder(null);
        formDK.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 250, -1));

        txtpassword.setBackground(new java.awt.Color(25, 118, 211));
        txtpassword.setForeground(new java.awt.Color(255, 255, 255));
        txtpassword.setBorder(null);
        formDK.add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 250, -1));

        show.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_eye_32px_2.png"))); // NOI18N
        show.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMouseClicked(evt);
            }
        });
        formDK.add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 27));

        jButton2.setBackground(new java.awt.Color(25, 118, 211));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back to Login");
        jButton2.setBorder(null);
        formDK.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password");
        formDK.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 170, -1, -1));

        lblMaNV.setForeground(new java.awt.Color(255, 255, 255));
        lblMaNV.setText("_________________________________");
        formDK.add(lblMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 290, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_contacts_32px_3.png"))); // NOI18N
        formDK.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 27));

        txtMaNV.setBackground(new java.awt.Color(25, 118, 211));
        txtMaNV.setForeground(new java.awt.Color(255, 255, 255));
        txtMaNV.setBorder(null);
        formDK.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 250, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formDK, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(formDK, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void disableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disableMouseClicked
        // TODO add your handling code here:
        txtpassword.setEchoChar((char)0);
        disable.setVisible(false);
        disable.setEnabled(false);
        show.setEnabled(true);
        show.setEnabled(true);

    }//GEN-LAST:event_disableMouseClicked

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        // kiểm tra xâu nhập vào có trống không 
        if (txtusername.getText().equals("")){
            sb.append(" Vui lòng nhập Username ! \n");
           
            txtusername.requestFocus();     
       
        }
        String password = new String(txtpassword.getText());
        if (password.equals("")){
            sb.append(" Vui lòng nhập Password ! \n");
        
            txtpassword.requestFocus();     
        }
        if (password.equals("")){
            sb.append(" Vui lòng nhập Password ! \n");
        
            txtpassword.requestFocus();     
        }
        if (txtMaNV.getText().equals("")){
            sb.append(" Vui lòng nhập Mã Nhân Viên ! \n");
        
            txtMaNV.requestFocus();     
        }
        if(sb.length()>0){
            JOptionPane.showMessageDialog(this,sb.toString());
            return;
        }
        TaiKhoan tk = new TaiKhoan();
        tk.setMaNhanVien(Integer.parseInt(txtMaNV.getText()));
        tk.setTenDangNhap(txtusername.getText());
        tk.setMatKhau(password);
        TaiKhoanController tkc = new TaiKhoanController();
        tkc.ThemTaiKhoan(tk);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void showMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMouseClicked
        // TODO add your handling code here:
        txtpassword.setEchoChar((char)8226);
        disable.setVisible(true);
        disable.setEnabled(true);
        show.setEnabled(false);
        show.setEnabled(false);

    }//GEN-LAST:event_showMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel disable;
    private javax.swing.JPanel formDK;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel show;
    private javax.swing.JPasswordField txtMaNV;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
